In [1]:
import pandas as pd
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [2]:
people = {
    "first": ["Corey", "John", "Jane"],
    "last": ["Shaufer", "Doe", "Doe"],
    "email": ["Corey@gmail.com", "John@yahoo.com", "Jane@ncit.edu.np"]
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last             email
0  Corey  Shaufer   Corey@gmail.com
1   John      Doe    John@yahoo.com
2   Jane      Doe  Jane@ncit.edu.np

In [5]:
df['full_name'] = df['first'] + ' ' + df['last']

In [6]:
df

   first     last             email      full_name
0  Corey  Shaufer   Corey@gmail.com  Corey Shaufer
1   John      Doe    John@yahoo.com       John Doe
2   Jane      Doe  Jane@ncit.edu.np       Jane Doe

In [7]:
df.drop(columns=['first','last'],inplace = True)

In [8]:
df

              email      full_name
0   Corey@gmail.com  Corey Shaufer
1    John@yahoo.com       John Doe
2  Jane@ncit.edu.np       Jane Doe

In [9]:
df.full_name.str.split(' ',expand=True)

       0        1
0  Corey  Shaufer
1   John      Doe
2   Jane      Doe

In [10]:
df = pd.concat([df,pd.Series(df['first'] + ' ' + df['last'],name='Full_name')],axis=1)

KeyError: 'first'

In [11]:
df

   first     last             email      Full_name
0  Corey  Shaufer   Corey@gmail.com  Corey Shaufer
1   John      Doe    John@yahoo.com       John Doe
2   Jane      Doe  Jane@ncit.edu.np       Jane Doe

In [26]:
df.drop('full_name',axis=1,inplace=True)

In [27]:
df

              email  first     last
0   Corey@gmail.com  Corey  Shaufer
1    John@yahoo.com   John      Doe
2  Jane@ncit.edu.np   Jane      Doe

In [53]:
df = pd.concat([df,pd.DataFrame({'email':['dip.231512@ncit.edu.np'],'first':['Dip Kiran']})],sort=False,ignore_index=True)

In [36]:
df

                    email      first     last
0         Corey@gmail.com      Corey  Shaufer
1          John@yahoo.com       John      Doe
2        Jane@ncit.edu.np       Jane      Doe
3  dip.231512@ncit.edu.np  Dip Kiran      NaN

In [52]:
df['full_name'] = df['first'] + df['last']

In [47]:
df

       first     last                   email     full_name
0      Corey  Shaufer         Corey@gmail.com  CoreyShaufer
1       John      Doe          John@yahoo.com       JohnDoe
2       Jane      Doe        Jane@ncit.edu.np       JaneDoe
3  Dip Kiran      NaN  dip.231512@ncit.edu.np           NaN

In [54]:
df = pd.concat([df,pd.Series([1,2,3,4],name="ID")],axis = 1)

In [55]:
df

       first     last                   email     full_name  ID
0      Corey  Shaufer         Corey@gmail.com  CoreyShaufer   1
1       John      Doe          John@yahoo.com       JohnDoe   2
2       Jane      Doe        Jane@ncit.edu.np       JaneDoe   3
3  Dip Kiran      NaN  dip.231512@ncit.edu.np           NaN   4

In [57]:
df.set_index("ID",inplace = True)

In [58]:
df

        first     last                   email     full_name
ID
1       Corey  Shaufer         Corey@gmail.com  CoreyShaufer
2        John      Doe          John@yahoo.com       JohnDoe
3        Jane      Doe        Jane@ncit.edu.np       JaneDoe
4   Dip Kiran      NaN  dip.231512@ncit.edu.np           NaN

In [60]:
df.drop(index = df[df['last']=='Shaufer'].index,inplace=True)

In [61]:
df

        first last                   email full_name
ID
2        John  Doe          John@yahoo.com   JohnDoe
3        Jane  Doe        Jane@ncit.edu.np   JaneDoe
4   Dip Kiran  NaN  dip.231512@ncit.edu.np       NaN

In [12]:
df

   first     last             email      Full_name
0  Corey  Shaufer   Corey@gmail.com  Corey Shaufer
1   John      Doe    John@yahoo.com       John Doe
2   Jane      Doe  Jane@ncit.edu.np       Jane Doe

In [19]:
df = pd.concat([df,pd.DataFrame({'first':['Dip'],'last':['rogers']})],axis=0,ignore_index=True,sort=False)

In [20]:
df

   first     last             email      Full_name
0  Corey  Shaufer   Corey@gmail.com  Corey Shaufer
1   John      Doe    John@yahoo.com       John Doe
2   Jane      Doe  Jane@ncit.edu.np       Jane Doe
3    Dip   rogers               NaN            NaN
4    Dip   rogers               NaN            NaN